export const ADD_PROJECT = 'ADD_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const SELECTED_PROJECT_ACTIVE = 'SELECTED_PROJECT_ACTIVE';
export const LAST_ACTIVE = 'LAST_ACTIVE';